name: LIARA
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
          port: 22
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
          
        run: |
          npm i -g @liara/cli@2
          liara deploy  --port 3000 --platform node --app themazlife --api-token="$LIARA_TOKEN" --region iran  --detach
